baseURL = "https://rolling.bangunan.co/"
languageCode = "id"
title = "Pasang Rolling Door | Pasang Rolling Door, Pintu Garasi Minimalis Modern"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Tukang Pasang Rolling Door - Borongan Pemasangan Rolling Door dan Pintu Garasi Minimalis Modern dengan harga terjangkau dan kualitas terbaik."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jasa pasang rolling door", "rolling door garasi", "tukang rolling door berpengalaman", "pintu rolling door minimalis", "rolling door besi", "rolling door aluminium"]
  base_price = 2500000
  price_range = 1000000
  free_consultation = true
  service_types = [
  "Pasang Rolling Door Garasi",
  "Pasang Rolling Door Besi",
  "Pasang Rolling Door Aluminium",
  "Pasang Rolling Door Minimalis",
  "Perbaikan Rolling Door"
  ]
  categories = ["Jasa Rolling Door", "Pintu Garasi", "Rolling Door"]
  payment_methods = ["Bayar Bertahap", "Transfer Bank", "Bayar DP 50%", "Transfer Setelah Selesai"]
  cancellation_policies = [
  "Layanan dapat dibatalkan jika tidak sesuai dengan kesepakatan.",
  "Pengembalian biaya jika hasil tidak memuaskan.",
  "Revisi gratis jika hasil pemasangan tidak rapih."
  ]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Subang", "Cikampek", "Purwakarta", "Rangkas Bitung", "Serang"]
  service_output = "Pintu garasi rolling door terpasang rapih sesuai permintaan"

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Pasang Rolling Door Berkualitas"
  hero_description = "Kami menawarkan layanan borongan pemasangan rolling door dan pintu garasi minimalis modern yang terjangkau dan berkualitas. Solusi ideal untuk keamanan dan tampilan modern bangunan Anda dengan bahan yang tahan lama dan desain yang elegan."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Rolling Door"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan layanan pemasangan rolling door dan pintu garasi minimalis modern yang berkualitas, harga terjangkau, dan layanan profesional. Konsultasi gratis untuk membantu Anda memilih produk yang sesuai dengan kebutuhan proyek Anda."

  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "rolling.bangunan.co menawarkan layanan pemasangan rolling door berkualitas dengan harga yang kompetitif. Kami mengutamakan kepuasan pelanggan dengan hasil kerja rapi, cepat, dan material tahan lama. Pilih kami untuk perlindungan dan keindahan rumah atau bangunan Anda dengan rolling door terbaik."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Saya {menggunakan|memanfaatkan|memakai} layanan {pemasangan|instalasi|penyediaan} rolling door dari rolling.bangunan.co untuk {garasi|pintu garasi|tempat parkir} rumah saya. Hasilnya {sangat rapi|terlihat rapi|rapi sekali|sangat bersih} dan {berkualitas tinggi|bermutu|luar biasa|premium}.|Layanan rolling.bangunan.co {membantu saya|membimbing saya|memberikan solusi untuk saya} dalam {memasang|menginstal|pemasangan} rolling door di garasi rumah saya. Hasil akhirnya {memuaskan|mengesankan|memenuhi harapan|melebihi ekspektasi} dan {rapi|sangat rapi|tertata dengan baik}.}"
  response = "{Terima kasih atas {kepercayaan|pilihan|dukungan} Anda! Kami senang dapat {menyediakan|menghadirkan|memberikan} rolling door {berkualitas|premium|bermutu} untuk {proyek|rumah|keperluan} Anda.|Kami sangat menghargai {kepercayaan|pilihan|keputusan} Anda. Terima kasih telah {memilih|mempercayai|menggunakan} produk kami!}"
  rating = "{4.5|5}"

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Dewi|Rina|Maya|Lina|Sari|Fitri|Nur|Diah|Ayu}"
  message = "{rolling.bangunan.co {membantu|mempermudah|mengarahkan} saya dalam {memilih|menentukan|memilah} dan {memasang|menginstal|menyediakan} rolling door yang {sangat sesuai|cocok sekali|tepat} dengan {kebutuhan|keperluan|preferensi} saya. Pelayanannya {memuaskan|sangat baik|luar biasa|ramah dan profesional}.|Saya sangat terbantu oleh rolling.bangunan.co dalam {memilih|memilah|menentukan} dan {memasang|menginstal|menyediakan} rolling door yang {sesuai|cocok|tepat} dengan kebutuhan saya. Pelayanannya {memuaskan|profesional|ramah}.}"
  response = "{Kami sangat menghargai ulasan Anda. {Senang mendengar|Kami gembira mengetahui|Bahagia mengetahui} bahwa Anda puas dengan rolling door dari kami.|Terima kasih atas ulasannya! Kami {senang|gembira|bahagia} Anda puas dengan {produk|layanan} dan {produk|solusi} kami.}"
  rating = "{4.6|5}"

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Bambang|Hadi|Tono|Gilang|Bayu|Faisal|Rizal|Ali|Ahmad}"
  message = "{Rolling door dari rolling.bangunan.co {sangat cocok|benar-benar tepat|sangat sesuai} untuk proyek {ruko|tempat usaha|properti komersial} saya. Pemasangannya {cepat|efisien|singkat} dan {profesional|rapi|tepat waktu}.|Saya sangat puas dengan {rolling door|produk} untuk ruko saya. Layanan rolling.bangunan.co {cepat|efisien|responsif} dan {profesional|berkualitas|sangat rapi}.}"
  response = "{Terima kasih! Kami {berkomitmen|fokus|dedikasi} untuk memberikan layanan terbaik dengan produk {berkualitas|premium|unggulan}.|Kami {menghargai|apresiasi|terima} ulasan Anda. Terima kasih telah {mempercayai|memilih|menggunakan} kami!}"
  rating = "{4|4.5}"

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Bayu|Fajar|Hendra|Dian|Rizky|Yoga|Yudi|Ari|Gani}"
  message = "{Saya sangat puas dengan {hasil|kualitas|proses} pemasangan rolling door dari rolling.bangunan.co. Pintu garasi saya terlihat {modern|elegan|keren} dan sangat {fungsional|praktis|berguna}.|Rolling door yang dipasang oleh rolling.bangunan.co membuat garasi saya tampak {modern|elegan|stylish} dan sangat {berguna|fungsional|efisien}.}"
  response = "{Senang mendengar Anda puas dengan {layanan|produk|hasil kerja} kami. Terima kasih atas {kepercayaannya|kepercayaannya|dukungan Anda}!|Kami {senang|bahagia|gembira} Anda puas dengan hasilnya. Terima kasih atas {kepercayaan|dukungan} Anda!}"
  rating = "{4.5|5}"

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Dewi|Lina|Ayu|Fitri|Sari|Diah|Nur|Maya}"
  message = "{Pelayanan rolling.bangunan.co sangat {memuaskan|baik|luar biasa}. Rolling door yang saya pesan {berkualitas|bermutu tinggi|premium} dan sesuai dengan {harapan|ekspektasi|keinginan}.|Saya sangat puas dengan {pelayanan|layanan} rolling.bangunan.co. Rolling door yang dipesan {berkualitas|bermutu|luar biasa} dan sesuai ekspektasi.}"
  response = "{Terima kasih! Kami senang dapat {mewujudkan|membantu dengan|melaksanakan} proyek Anda dengan rolling door {terbaik|berkualitas|unggulan}.|Kami {menghargai|terima kasih atas} ulasan Anda. Terima kasih telah {memilih|mempercayai|menggunakan} kami untuk proyek Anda!}"
  rating = "{4.6|5}"

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Agus|Dedi|Toni|Yanto|Wawan|Benny|Rio|Iwan|Galih}"
  message = "{Rolling door dari rolling.bangunan.co sangat {sesuai|cocok|tepat} untuk garasi saya. Proses pemasangan {cepat|efisien|singkat} dan {aman|lancar|berjalan mulus}.|Saya sangat puas dengan {produk|rolling door} dari rolling.bangunan.co. Proses pemasangan {aman|lancar|terorganisir} dan {cepat|efisien|singkat}.}"
  response = "{Kami senang mendengar bahwa Anda puas dengan produk kami. Terima kasih atas {ulasannya|tanggapan positifnya}!|Terima kasih telah {mempercayai|menggunakan|memilih} kami untuk proyek ini. Kami {senang|bahagia|gembira} Anda puas dengan hasilnya.}"
  rating = "{5|4.8}"

[[params.tabelItems]]
  name = "Pasang Rolling Door Garasi"
  price = "500.000 /m"
[[params.tabelItems]]
  name = "Pasang Rolling Door Besi"
  price = "1.800.000 /m"
[[params.tabelItems]]
  name = "Pasang Rolling Door Aluminium"
  price = "2.400.000 /m"
[[params.tabelItems]]
  name = "Pasang Rolling Door Kayu"
  price = "1.500.000 /m"
[[params.tabelItems]]
  name = "Perbaikan Rolling Door"
  price = "700.000 /m"

[params.appliList]
  "Pasang Rolling Door Garasi" = "garasi rumah, ruko"
  "Pasang Rolling Door Besi" = "garasi, toko, gudang"
  "Pasang Rolling Door Aluminium" = "pintu garasi, showroom"
  "Pasang Rolling Door Minimalis" = "pintu garasi rumah minimalis"
  "Perbaikan Rolling Door" = "perbaikan dan servis rolling door yang rusak"

[params.kegunaanList]
  "Pasang Rolling Door Garasi" = "melindungi kendaraan dengan rolling door yang aman"
  "Pasang Rolling Door Besi" = "memberikan keamanan ekstra dengan pintu yang kuat"
  "Pasang Rolling Door Aluminium" = "desain modern dan ringan untuk kemudahan penggunaan"
  "Pasang Rolling Door Minimalis" = "tampilan minimalis untuk bangunan modern"
  "Perbaikan Rolling Door" = "memperbaiki rolling door agar berfungsi normal kembali"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Layanan Pemasangan Rolling Door & Pintu Garasi Modern | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"